# CI de Nível 01 - Disparo Manual através de clique

# nome da pipeline
stages:
  - Execução manual

# tarefas dentro da pipeline = jobs

# nome do job
e2e-tests:
  # estágio onde o job será executado
  stage: test

  # maquina/container onde o job vai rodar
  image: node:24

  # gatilho manual = when: manual
  when: manual

  # passos executados antes dos testes
  before_script:
    # instalação do Yarn
    - npm install -g yarn

    # instalação das dependências
    - yarn

    # instalação dos Browsers do Playwright
    - yarn playwright install

  # passos principais do job
  script:
    # executar os testes e2e
    - yarn run e2e